FROM node:6.10.0-alpine

RUN mkdir /app

COPY ./package.json /app/

# Set a working directory
WORKDIR /app

# Install Node.js dependencies
RUN npm install

RUN npm install node-pre-gyp

RUN npm install sqlite3

COPY ./ /app

#EXPOSE 3000

#CMD [ "npm", "run", "start" ]
