version: '2'
services:
  web:
    build:
      context: ../
      dockerfile: './docker/Dockerfile.local'
    command: npm run start
    ports:
     - "8081:3000"
    volumes:
     - ../:/app
     - /app/node_modules
