version: '2'
services:
  web:
    build:
      context: .
      dockerfile: './Dockerfile.local'
    command: npm run start
    ports:
     - "8081:3000"
    volumes:
     - .:/app
     - /app/node_modules
