FROM node:6.9.5-alpine

ARG KENDO_USERNAME
ARG KENDO_PASSWORD

RUN mkdir /app

COPY ./package.json /app/

# Set a working directory
WORKDIR /app

RUN npm install -g yarn

# Install Node.js dependencies
RUN yarn install

RUN rm -rf ~/.netrc

RUN printf "machine bower.telerik.com\n\tlogin $KENDO_USERNAME\n\tpassword $KENDO_PASSWORD" > ~/.netrc

CMD [ "npm", "run", "start" ]
